#include "zcommon.acs"

script 1 OPEN {
    Delay(1);
    Print(s:"Hi");
    Delay(5);
    Print(s:"Hi again!");
    Print(i:4);
}

script 2 (void) {
    Print(s:"Hello from script 2");
}
script "Named" (void) {
    Print(s:"Hello from a named script");
}

script "ReturnsResult" (void) {
    SetResultValue(500);
}

script "UsesALineSpecial" (void) {
    int value = Door_Open(10, 32);
    Print(s:"Return value: ", i:value);
}
script "UsesTagWait" (void) {
    Print(s:"Pre-wait");
    TagWait(10);
    Print(s:"Post-wait");
}
script "UsesRandom" (void) {
    Print(i:Random(0, 7));
    Print(i:Random(4, 15));
    Print(i:Random(-5, 12));
}
script "UsesGetActorVelX" (void) {
    Print(f:GetActorVelX(5));
    Print(f:GetActorVelX(4));
}
script "UsesSpawn" (void) {
    Print(i:Spawn("something", 1, 2, 3));
}

int something;
world int 1:somethingWorld;
global int 2:somethingGlobal;
script "ModifiesState" (void) {
    Print(i:something, s:" ", i:somethingWorld, s:" ", i:somethingGlobal);
    something += 1;
    somethingWorld += 1;
    somethingGlobal += 1;
}
